# Generated by Django 3.0.2 on 2020-01-09 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Athlete',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('sex', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'athlete',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, null=True, unique=True)),
            ],
            options={
                'db_table': 'city',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, null=True, unique=True)),
            ],
            options={
                'db_table': 'event',
            },
        ),
        migrations.CreateModel(
            name='Games',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'games',
            },
        ),
        migrations.CreateModel(
            name='Medal',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, null=True, unique=True)),
            ],
            options={
                'db_table': 'medal',
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, null=True, unique=True)),
            ],
            options={
                'db_table': 'season',
            },
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, null=True, unique=True)),
            ],
            options={
                'db_table': 'sport',
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'db_table': 'team',
            },
        ),
        migrations.CreateModel(
            name='Attributes',
            fields=[
                ('age', models.IntegerField(null=True)),
                ('height', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('year', models.IntegerField(null=True)),
                ('athlete', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='api.Athlete')),
            ],
            options={
                'db_table': 'attributes',
            },
        ),
        migrations.AddField(
            model_name='athlete',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.City'),
        ),
        migrations.AddField(
            model_name='athlete',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Event'),
        ),
        migrations.AddField(
            model_name='athlete',
            name='games',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Games'),
        ),
        migrations.AddField(
            model_name='athlete',
            name='medal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Medal'),
        ),
        migrations.AddField(
            model_name='athlete',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Season'),
        ),
        migrations.AddField(
            model_name='athlete',
            name='sport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Sport'),
        ),
        migrations.AddField(
            model_name='athlete',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Team'),
        ),
    ]
