# Generated by Django 3.0.2 on 2020-01-08 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributes',
            name='height',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='attributes',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
    ]
